name: ⭐ Generate Stared Repo List

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Generate the list
      - name: Create star list
        id: stargazer
        uses: rverst/stargazer@v1.2.6
        with:
          github-user: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          list-file: "README.md"
          ignored-repositories: ${{ secrets.IGNORE_REPO }}
          with-back-to-top: true

      # Commit the changes
      - name: Commit files
        run: |
          git config --local user.email "araguaci@gmail.com"
          git config --local user.name "github-actions [bot]"
          git add .
          git commit -m "Update stargazer list"

      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
